### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by andzejsp** [nomic-ai/gpt4all-ui#66] opened 2023-04-10 17:04 UTC
## Expected Behavior
Please describe the behavior you are expecting.
Installed using install.bat
Downloaded model via browser option
Converted this model. 
Install completed.
opened Run.bat
it works?

## Current Behavior
Please describe the behavior you are currently experiencing.
open run.bat
gets error
```
HHHHHHHHHHHHH.##  HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH#.HHHHH/*,*,*,*,*,*,*,*,***,*,**#HHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHH.*,,***,***,***,***,***,***,*******HHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*,,,,,HHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH.,,,***,***,***,***,***,***,***,***,***,***/HHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH*,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHH#,***,***,***,***,***,***,***,***,***,***,***,**HHHHHHHHHHHHHHHHH                                        HHHHHHHHHHHHH.##  HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH#.HHHHH/*,*,*,*,*,*,*,*,***,*,**#HHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHH.*,,***,***,***,***,***,***,*******HHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*,,,,,HHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH.,,,***,***,***,***,***,***,***,***,***,***/HHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH*,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHH#,***,***,***,***,***,***,***,***,***,***,***,**HHHHHHHHHHHHHHHHH
HHHHHHHHHH..HHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*#HHHHHHHHHHHHHHHH
HHHHHHH,,,**,/H*,***,***,***,,,*,***,***,***,**,,,**,***,***,***H,,*,***HHHHHHHH
HHHHHH.*,,,*,,,,,*,*,*,***#HHHHH.,,*,*,*,*,**/HHHHH.,*,*,*,*,*,*,*,*****HHHHHHHH
HHHHHH.*,***,*,*,***,***,.HHHHHHH/**,***,****HHHHHHH.***,***,***,*******HHHHHHHH
HHHHHH.,,,,,,,,,,,,,,,,,,,.HHHHH.,,,,,,,,,,,,.HHHHHH,,,,,,,,,,,,,,,,,***HHHHHHHH
HHHHHH.,,,,,,/H,,,**,***,***,,,*,***,***,***,**,,,,*,***,***,***H***,***HHHHHHHH
HHHHHHH.,,,,*.H,,,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,***H*,,,,/HHHHHHHHH
HHHHHHHHHHHHHHH*,***,***,**,,***,***,***,***,***,***,***,***,**.HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH,,,,,,,,*,,#H#,,,,,*,,,*,,,,,,,,*#H*,,,,,,,,,**HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH,,*,***,***,**/.HHHHHHHHHHHHH#*,,,*,***,***,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,***,***,***,***,***,***,***,***,*.HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,*******/..HHHHHHHHH.#/*,*,,,***,***HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH*,*,*,******#HHHHHHHHHHHHHHHHHHHHHHHHHHHH./**,,,.HHHHHHHHHHHHHH
Checking discussions database...HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.*#HHHHHHHHHHHH
llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
Traceback (most recent call last):
  File "E:\Git_repos\gpt4all-ui\app.py", line 441, in <module>
    bot = Gpt4AllWebUI(app, args)
  File "E:\Git_repos\gpt4all-ui\app.py", line 86, in __init__
    self.prepare_a_new_chatbot()
  File "E:\Git_repos\gpt4all-ui\app.py", line 102, in prepare_a_new_chatbot
    self.condition_chatbot()
  File "E:\Git_repos\gpt4all-ui\app.py", line 118, in condition_chatbot
    if self.db.does_last_discussion_have_messages():
  File "E:\Git_repos\gpt4all-ui\db.py", line 153, in does_last_discussion_have_messages
    last_discussion_id = self.select("SELECT id FROM discussion ORDER BY id DESC LIMIT 1", fetch_all=False)[0]
TypeError: 'NoneType' object is not subscriptable
```
## Steps to Reproduce
Please provide detailed steps to reproduce the issue.
Installed using install.bat
Downloaded model via browser option
Converted this model. 
Install completed.
opened Run.bat

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by macronomicus** [comment] 2023-04-10 17:12
Was just about to post this as well. At first I thought it was from doing a git pull of latest code, so I uninstalled & deleted everything then started over, still get same error as you got, no errors on install, only this one when running run.bat
It was working fine before, so its recent changes that did this.

**Comment by andzejsp** [comment] 2023-04-10 17:13
i just installed this, i have no notion of previous versions :(

**Comment by macronomicus** [comment] 2023-04-10 17:15
I am on windows 10, what OS are you using?

It worked great before so hopefully someone will figure which recent commit caused the bug, or some way to resolve it. 
Looking at the error is not apparent to me yet what the fix might be.

**Comment by andzejsp** [comment] 2023-04-10 17:20
I am on windows 11. Few hours ago i tried to install this on debian 11 but got different error with illegal action or some sore of that type of error.

I really have no idea how to debug this. Wanted to see how smooth this works compared to GPT3.5

**Comment by andzejsp** [comment] 2023-04-10 17:25
> It works really surprisingly well, very impressive, for me its also very fast on my CPU an AMD ryzen 5900x YMMV.
> 
> I will keep tinkering, but not sure im capable of fixing it lol
> 
> I just noticed in the releases page there's a release from 4 days ago, I will test installing that instead to see if it fixes it, perhaps using git clone on the main branch was not best way lol.

i tried that release, it gives me error check internet connection, cant even download the packages it needs when running install.bat.

I got 5900x too and 3090 :), also i wanted to test other models too, given that they need more ram/vram

**Comment by macronomicus** [comment] 2023-04-10 17:29
I think this ai is far more reliant on CPU than others tend to be, except perhaps for training that is, ive not tried to train anything with it yet so I dunno.  

Hopefully others are hitting this bug now & will report it too, or someone might guess at a fix, I was all excited to sit and chat with it again.

**Comment by andzejsp** [comment] 2023-04-10 17:30
I saw a video on youtube and was interested to toest it. It failed to install for me on debina, then when i got home, it even failed to install on windows :(. Oh well, gotta wait for devs to fix this. Gonna try out tomorrow

**Comment by macronomicus** [comment] 2023-04-10 17:42
I can see the errors are being thrown by this recent commit. The lines in question are new.

https://github.com/nomic-ai/gpt4all-ui/commit/a431586f053f80965aa13f5d53c442acf2bfeb7e

**Comment by rootdevelop** [comment] 2023-04-10 17:47
Exactly the same issue on macOS (M1 Pro):

```
Traceback (most recent call last):
  File "/Users/hermes/Developer/gpt4all-ui/app.py", line 441, in <module>
    bot = Gpt4AllWebUI(app, args)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hermes/Developer/gpt4all-ui/app.py", line 86, in __init__
    self.prepare_a_new_chatbot()
  File "/Users/hermes/Developer/gpt4all-ui/app.py", line 102, in prepare_a_new_chatbot
    self.condition_chatbot()
  File "/Users/hermes/Developer/gpt4all-ui/app.py", line 118, in condition_chatbot
    if self.db.does_last_discussion_have_messages():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hermes/Developer/gpt4all-ui/db.py", line 153, in does_last_discussion_have_messages
    last_discussion_id = self.select("SELECT id FROM discussion ORDER BY id DESC LIMIT 1", fetch_all=False)[0]
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by BriannaBromell** [comment] 2023-04-10 17:49
Same issue qq

**Comment by macronomicus** [comment] 2023-04-10 17:50
Ok so thats Windows & Mac, could it be something in that commit I posted is linux specific? 
Perhaps thats why they didnt notice the bug when testing.

**Comment by macronomicus** [comment] 2023-04-10 17:53
Found this, but not sure how to remedy, seems it could be the **fetch_all=False)[0]** on line 153 of db.py

" In general, the error means that you attempted to index an object that doesn't have that functionality. You might have noticed that the method sort() that only modify the list have no return value printed – they return the default None. This is a design principle for all mutable data structures in Python.

This TypeError is the one thrown by python when you use the square bracket notation object[key] where an object doesn't define the __getitem__ method . You can reproduce TypeError that you get in your code if you try this at the Python command line:"
https://net-informations.com/python/err/nonetype.htm

**Comment by andzejsp** [comment] 2023-04-10 17:56
ok but how do you fix it? im no python expert.

**Comment by macronomicus** [comment] 2023-04-10 18:02
I have no idea either, have never worked with python before, **fetch_all=False)[0]** is used several times in db.py & is coming from **def select** starting at line 76 which returns the cursor object.  But I havnt a clue how to " define the getitem method" or if thats even the reason we're getting a nonetype error. 😅

**Comment by andzejsp** [comment] 2023-04-10 18:03
the way i see it someone forgot to initiate db with empty data. thats why it cant pull from db.

**Comment by macronomicus** [comment] 2023-04-10 18:09
Ahh that seems possible, would explain why they didnt notice anything because their db had stuff so the **if self.current_discussion is None:**  never fired for them.

I did have it installed and working though, when I did a git pull then started again it was no longer working with other issues, so I scrapped it and started fresh which lead me here.  I might try reverting the commit I linked above & see if it actually is that commit that caused the troubles.

**Comment by macronomicus** [comment] 2023-04-10 18:39
Ok so not a fix but it does get it working, just resetting your local code to the commit before the Enhanced Ui commits.  I tested and its working, chatting and all.

`git reset --hard 32a45fc2c5f14bba551e63d70826775ae3c70697`

**Comment by andzejsp** [comment] 2023-04-10 18:49
> Ok so not a fix but it does get it working, just resetting your local code to the commit before the Enhanced Ui commits. I tested and its working, chatting and all.
> 
> `git reset --hard 32a45fc2c5f14bba551e63d70826775ae3c70697`

thanks, this worked for me :)

**Comment by ParisNeo** [comment] 2023-04-10 19:00
Hi gues. I understand the error. Mybad. I have made this update to the database without testing the case where the database is empty.
I'll correct the problem and commit the update.

**Comment by ParisNeo** [comment] 2023-04-10 19:19
It should work now.
Sorry, I made too many changes and didn't test all cases. I need to add some unit tests for this all once it is stable.

Bare with me as I still wait the updates from the python bindings team to accelerate the generation process. Now when you post a message, I have to wait fror the model to first spit out your prompt then start spitting the model output, which, as you may expect makes it really slow to the end user. You can see data coming on the terminal but in the UI I only start updating once the model output starts pooring.

One this is corrected, the application will be way more easy to use.

**Comment by macronomicus** [comment] 2023-04-10 19:40
Cheers! 
Yea I noticed that it was going thru the whole text again so slower than before, seemed to also hit a prompt limit since its counting all of previous prompts in the character limit, I thought that might have been due to my doing the reset to previous commit though. I will test again with your latest changes. Thanks again for working on this!

**Comment by macronomicus** [comment] 2023-04-10 19:59
Ok I tested again, everything loaded up fine, so I think you've sorted the issue with empty db.

I went ahead & also tested the token limit & it did hit that after a handful of prompts, but thats unrelated to this particular issue with the empty db of course.

**Comment by ParisNeo** [comment] 2023-04-10 20:25
Thank, you. I'll close the issue then.
As of the token limit it is a parameter ctx_size that you can pass to the run script or the app.py scrpipt. by default it is 512.

**Closed by ParisNeo** 2023-04-10 20:25 UTC
